### ISSUE TITLE
Pivot Columns / Group Header Incompatibility as of 6.5.2

### ISSUE THREAD

**Issue by scrawfor** [react-tools/react-table#472]
## What version of React-Table are you using?
6.5.3 & 6.5.2,  Working as of 6.5.1

## What bug are you experiencing?
The table does not render when you have a configuration with pivoted columns that are not grouped and aggregated columns which are grouped. If all columns are grouped, three is no issue.

```javascript
Uncaught TypeError: Cannot read property 'Header' of undefined
```

```javascript
        let PivotParentColumn = pivotColumns.reduce(
          (prev, current) =>
            prev && prev === current.parentColumn && current.parentColumn,
          pivotColumns[0].parentColumn
        )

        let PivotGroupHeader = hasHeaderGroups && PivotParentColumn.Header
        PivotGroupHeader = PivotGroupHeader || (() => <strong>Pivoted</strong>)
```

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
Broken (6.5.3):  _Notice that first and last name are not grouped_
https://codesandbox.io/s/wyvor42vw

Working (6.5.3)  _Notice that first and last name are now grouped_
https://codesandbox.io/s/n780jz8600

Working (6.5.1): _First and last name are not grouped, but the table is still working_
https://codesandbox.io/s/l599vz8277

## What are the steps to reproduce the issue?
1. Have a configuration where you have pivot columns which are not grouped and aggregated columns which are grouped.
2. Render the table

**Comment by tannerlinsley** [comment]
This should be fixed in the latest version

**Comment by traysh** [comment]
It seems this was never fixed. I tried with every version from 6.5.2 to 6.7.6 and it's not working.

**Comment by traysh** [comment]
It won't currently work with the code provided by scrawfor because it defines parents for every columns except the pivoted ones. If no columns have parents, it works.

**Comment by michaelbridge** [comment]
Still not working.  Considering a fork as this is mission-critical.

**Comment by RyanCCollins** [comment]
I am having this issue as well.

**Comment by emiraga** [comment]
This is not fixed, workaround is to put pivoted column into a header group as well.
